<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>InteractifLive.PlanetCrafter.GamePass</AssemblyName>
    <RootNamespace>InteractifLive.PlanetCrafter.GamePass</RootNamespace>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="src\PluginGamePass.cs" />
    <Compile Include="src\CompilerCompatibility.cs" />
    <Reference Include="BepInEx.Core"><HintPath>$(BepInEx6Dir)\BepInEx.Core.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx.Unity.IL2CPP"><HintPath>$(BepInEx6Dir)\BepInEx.Unity.IL2CPP.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(BepInEx6Dir)\..\interop\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2Cppmscorlib"><HintPath>$(BepInEx6Dir)\..\interop\Il2Cppmscorlib.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Il2CppInterop.Runtime"><HintPath>$(BepInEx6Dir)\Il2CppInterop.Runtime.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
